version: "2"

checks:
  method-complexity:
    enabled: true
    config:
      threshold: 10
  method-count:
    enabled: true
    config:
      threshold: 30

plugins:
  flog:
    enabled: true
    config:
      score_threshold: 30.0
