name: Ruby

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        ruby-version: [2.7.6, 3.0.4, 3.1.2]
        gem-version: [3.3.15]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1.113.3
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true
    - name: Use RubyGems with the specific version
      env:
        gemver: ${{ matrix.gem-version }}
      run: |
        gem update --system $gemver
        gem --version
    - name: Run tests
      env:
        MINITEST_REPORTER: SpecReporter
      run: bundle exec rake
      continue-on-error: ${{ matrix.continue-on-error }}
    - name: Workaround for coverage report to CodeClimate with jq
      if: startsWith(matrix.ruby-version, '3.1')
      run: |
        jq 'map_values(. | map_values(if type=="object" then map_values(.lines) else . end))' coverage/.resultset.json > coverage/.resultset_workaround.json
        diff -uw coverage/.resultset.json coverage/.resultset_workaround.json || true
    - name: Send coverage report to CodeClimate
      if: startsWith(matrix.ruby-version, '3.1')
      continue-on-error: true
      uses: paambaati/codeclimate-action@v3.0.0
      with:
        coverageLocations: ${{ github.workspace }}/coverage/.resultset_workaround.json:simplecov
      env:
        CC_TEST_REPORTER_ID: 7fb735382fb47329991488219f04e879295d227e6674b8a34edfe6c76cd0c8b7

  rubocop:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1.113.3
      with:
        ruby-version: 3.1.2
    - name: Run RuboCop
      run: |
        bundle add rubocop --version 1.31.0
        bundle add rubocop-minitest --version 0.20.1
        bundle add rubocop-rake --version 0.6.0
        bundle exec rubocop
